version: "3.9"

services:
  web:
    build: .
    ports:
      - "6060:80"
    volumes:
      - .:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db/01-create-database.sql:/docker-entrypoint-initdb.d/01-create-database.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "6061:80"
    environment:
      PMA_HOST: db
      PMA_USER: usuario
      PMA_PASSWORD: usuario123

volumes:
  db_data:
